import logger from 'debug'

/**
 * Middleware for catching errors thrown in routes
 * @param ctx
 * @returns {function}
 */
export default async(ctx, next) => {
  try {
    await next()
  } catch(error) {
    if (error.constructor.name !== 'Exception') {
      throw error
    }

    // Errors generated by our app (ex: Wrong login)
    // don't need to log the whole stacktrace
    logger('app:error')(error.message)
    ctx.status = 400
    ctx.body = {
      message: error.message
    }
  }
}
